# Generated by Django 4.1.4 on 2023-01-03 06:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_joblog_misc_alter_joblog_task_runtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 1, 3, 6, 38, 16, 858416, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='joblog',
            name='job_end_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='joblog',
            name='job_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='joblog',
            name='job_started_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='joblog',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='joblog',
            name='task_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='joblog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
