# Generated by Django 4.1.4 on 2023-01-03 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_joblog_created_at_joblog_job_end_at_joblog_job_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblog',
            name='task_id',
            field=models.UUIDField(null=True),
        ),
    ]
